### ISSUE TITLE
`brew-pkg` failing

### ISSUE THREAD

**Issue by viferga** [metacall/distributable-macos#15]
It seems to fail, maybe it is because brew is too new and for `brew pkg` command, maybe we need to fork it and update it, or implement it by ourselves, or maybe it is a simpler bug, I haven't checked it.

```
+ brew pkg --with-deps --without-kegs metacall
==> Creating package staging root using Homebrew prefix /opt/homebrew
Error: undefined method `exists?' for class File
Error: undefined method `exists?' for class File
==> Staging formula metacall
/opt/homebrew/bin/brew-pkg.rb:74:in `block in pkg'
/opt/homebrew/bin/brew-pkg.rb:65:in `each'
/opt/homebrew/bin/brew-pkg.rb:65:in `pkg'
/opt/homebrew/bin/brew-pkg.rb:162:in `<top (required)>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'
You have disabled automatic updates and have not updated today.
Do not report this issue until you've run `brew update` and tried again.
```

https://github.com/metacall/distributable-macos/actions/runs/9556194327/job/26342635930

**Comment by viferga** [comment]
> It seems to fail, maybe it is because brew is too new and for `brew pkg` command, maybe we need to fork it and update it, or implement it by ourselves, or maybe it is a simpler bug, I haven't checked it.
> 
> ```
> + brew pkg --with-deps --without-kegs metacall
> ==> Creating package staging root using Homebrew prefix /opt/homebrew
> Error: undefined method `exists?' for class File
> Error: undefined method `exists?' for class File
> ==> Staging formula metacall
> /opt/homebrew/bin/brew-pkg.rb:74:in `block in pkg'
> /opt/homebrew/bin/brew-pkg.rb:65:in `each'
> /opt/homebrew/bin/brew-pkg.rb:65:in `pkg'
> /opt/homebrew/bin/brew-pkg.rb:162:in `<top (required)>'
> <internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> <internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
> /opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
> /opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'
> You have disabled automatic updates and have not updated today.
> Do not report this issue until you've run `brew update` and tried again.
> ```
> 
> https://github.com/metacall/distributable-macos/actions/runs/9556194327/job/26342635930

@FirePing32

**Comment by FirePing32** [comment]
Will look into it.
